### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'pyopenssl>=16.0.0; extra == "tls"' distribution was not found and is required by twisted

### ISSUE THREAD

**Issue by arthurlutz** [LeastAuthority/tahoe-gui#5]
on ubuntu yakkety in a virtualenv I get the following traceback

```
$ python3.5 -m pip install git+https://github.com/LeastAuthority/tahoe-gui.git
[snip]
$ tahoe-gui 
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/tahoe-gui/bin/tahoe-gui", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/arthur/.virtualenvs/tahoe-gui/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2976, in <module>
    @_call_aside
  File "/home/arthur/.virtualenvs/tahoe-gui/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2962, in _call_aside
    f(*args, **kwargs)
  File "/home/arthur/.virtualenvs/tahoe-gui/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2989, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/arthur/.virtualenvs/tahoe-gui/lib/python3.5/site-packages/pkg_resources/__init__.py", line 660, in _build_master
    ws.require(__requires__)
  File "/home/arthur/.virtualenvs/tahoe-gui/lib/python3.5/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/arthur/.virtualenvs/tahoe-gui/lib/python3.5/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyopenssl>=16.0.0; extra == "tls"' distribution was not found and is required by twisted
```

**Comment by arthurlutz** [comment]
```
pip install pyopenssl
pip install pyopenssl[tls]
pip install service-identity[tls]
```
seems to have fixed the problem (don't know which one precisely).

**Comment by meejah** [comment]
What version of virtualenv/pip comes with that Ubuntu? On Debian I always do `pip install --upgrade pip` in new virtualenvs because it's 1.5.6 or something ancient.

**Comment by djbill** [comment]
Hi, I solved the issue doing

`pip install twisted[tls]`
